# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml.
# All the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Signup"

#startup_info: 1
server_tokens: 0

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# When the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
template: "template_toolkit"
engines:
  template_toolkit:
    start_tag: "[%"
    end_tag:   "%]"
    PLUGINS:
      ttutils: "CTSMS::BulkProcessor::Projects::WebApps::Signup::TTPlugin"
    ENCODING: "utf8"

#plugins:
#  I18N:
#    name_param: lang
#    name_session: lang
#    directory: i18n11
#    lang_default: en
    #maketext_options:
    #   Style: maketext
#      Decode: 0